package gcm

import "github.com/stretchr/testify/mock"

import "time"

// xmppClientMock is an autogenerated mock type for the xmppClient type
type xmppClientMock struct {
	mock.Mock
}

// close provides a mock function with given fields: graceful
func (_m *xmppClientMock) close(graceful bool) error {
	ret := _m.Called(graceful)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(graceful)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// isClosed provides a mock function with given fields:
func (_m *xmppClientMock) isClosed() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// listen provides a mock function with given fields: h
func (_m *xmppClientMock) listen(h MessageHandler) error {
	ret := _m.Called(h)

	var r0 error
	if rf, ok := ret.Get(0).(func(MessageHandler) error); ok {
		r0 = rf(h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ping provides a mock function with given fields: timeout
func (_m *xmppClientMock) ping(timeout time.Duration) error {
	ret := _m.Called(timeout)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = rf(timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// send provides a mock function with given fields: m
func (_m *xmppClientMock) send(m XMPPMessage) (string, int, error) {
	ret := _m.Called(m)

	var r0 string
	if rf, ok := ret.Get(0).(func(XMPPMessage) string); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(XMPPMessage) int); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(XMPPMessage) error); ok {
		r2 = rf(m)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ID provides a mock function with given fields:
func (_m *xmppClientMock) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
